# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 13, 27, 43, 527892, tzinfo=utc)),
        ),
    ]
