# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0003_auto_20160524_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-published', '-rating', '-is_correct']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 15, 43, 48, 598261, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='Test', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 15, 43, 48, 597143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
