# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0004_auto_20160524_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_app.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 15, 46, 7, 388753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 15, 46, 7, 387315, tzinfo=utc)),
        ),
    ]
