# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0005_auto_20160524_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 16, 22, 10, 983995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 16, 22, 10, 982131, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Question'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Answer'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile'),
        ),
    ]
