# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0006_auto_20160524_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 13, 12, 0, 360811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Answer'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 13, 12, 0, 358258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Profile'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Question'),
        ),
    ]
