# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0007_auto_20160531_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 13, 51, 21, 314840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 13, 51, 21, 313388, tzinfo=utc)),
        ),
    ]
